version: '2'
services:

  mongo:
    mem_limit: 50m
    image: mongo:latest
    container_name: mongo
    volumes:
      - /srv/docker/mongodb:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    restart: always

  server:
    tty: true
    mem_limit: 250m
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8090:3000"
    command: yarn start
    env_file:
      - ./server/.env

  client:
    tty: true
    mem_limit: 250m
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
